services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        # base64 encoded GAMS License
        - GAMS_LICENSE=${GAMS_LICENSE}
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:8080"
    networks:
      - traefik_web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_web"
      - "traefik.http.routers.toolbox-server-${ENV_MODE}.rule=Host(`${URL_SERVER}`)"
      - "traefik.http.routers.toolbox-server-${ENV_MODE}.entrypoints=websecure"
      - "traefik.http.routers.toolbox-server-${ENV_MODE}.tls.certResolver=letsencrypt"

networks:
  traefik_web:
    external: true
